server:
  port: 80
  servlet:
    encoding: 
      charset: utf-8
      force: true 

spring: 
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/kender_rent?serverTimeZone=Asia/Seoul 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1234
  h2:
    console:
      enabled: false
  sql:
    init:
      encoding: utf-8
      data-locations:
        - classpath:db/data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: true
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      fail-on-empty-beans: false
file:
  path: ./images/
  
mybatis:
 mapper-locations:
  classpath:mapper/**.xml
 configuration:
  map-underscore-to-camel-case: true
  
logging:
 level:
  org.mybatis: DEBUG

#초기 파라미터 설정
#tenco:
#  key: 1234567890!