server:
  port: 80
  servlet:
    encoding: 
      charset: utf-8
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
#    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/kender_rent?serverTimeZone=Asia/Seoul 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1234
  h2:
    console:
      enabled: false
  sql:
    init:
      encoding: utf-8
      schema-locations:
        classpath:db/table.sql
      data-locations:
        classpath:db/data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: true
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: bxQuRgVT_baVA8Siz5vc
            client-secret: K2EMahe2on
            client-name: Naver
            redirect-uri: http://localhost/user/naver-callback
            authorization-grant-type: authorization_code
            scope:
              -name
              -email
              -nickname
              -mobile
          kakao:
            client-id: 271d310fa59cc2d79b4807e9b895349d
            client-secret: oc953Ik0r4lFU5gbkUyGisfDk3vhEvxC
            client-name: Kakao
            client-authentication-method: POST
            redirect-uri: http://localhost/user/kakao-callback
            authorization-grant-type: authorization_code
            scope:
              -profile_nickname
              -account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
  mail:
    host: smtp.naver.com
    port: 465
    username: m40ro1988@naver.com
    password: t1prjKinderlend
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
file:
  path: ./images/
  
mybatis:
 mapper-locations:
  classpath:mapper/**.xml
 configuration:
  map-underscore-to-camel-case: true
  
logging:
 level:
  org.mybatis: DEBUG

#초기 파라미터 설정
tenco:
  key: 1234567890!
kakao:
  key: 85a9fbeacd6dee03b7157c7360812509

# static 폴더

## S3
#cloud:
#  aws:
#    s3:
#      bucket: kinder-rent
#    stack:
#      auto: false
#    region:
#      static: ap-northeast-2
#    credentials:
#      access-key: AKIAWQNL7AUQACCSLTTB
#      secret-key: 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