spring:
  profiles:
    active:
      - dev

## S3
#cloud:
#  aws:
#    s3:
#      bucket: kinder-rent
#    stack:
#      auto: false
#    region:
#      static: ap-northeast-2
#    credentials:
#      access-key: AKIAWQNL7AUQACCSLTTB
#      secret-key: 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