server:
  port: 80
  servlet:
    encoding: 
      charset: utf-8
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
#    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/kender_rent?serverTimeZone=Asia/Seoul 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1234
  h2:
    console:
      enabled: false
  sql:
    init:
      encoding: utf-8
      schema-locations:
        classpath:db/table.sql
      data-locations:
        classpath:db/data.sql
  
  
  
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
    host: smtp.naver.com
    port: 465
    username: m40ro1988@naver.com
    password: t1prjKinderlend
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naber.com
      mail.smtp.starttls.enable: true
coolsms:
  api:
    key: NCSTKLOBSUZP57OY
    secret: RWF9BWRRSFGZQLADHFGYDK2YAMK1ZHMU
  phoneNumber: 01022217307
file:
  path: ./static/images/
  
mybatis:
  mapper-locations:
    - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    org.mybatis: DEBUG
#초기 파라미터 설정
tenco:
  key: C775E7B757EDE630CD0AA1113BD102661AB38829CA52A6422AB782862F268646

kakao:
  key: 0a29e10b57cb7259eec5a50bdced4aa7

naver:
  clientkey: LbaGbefoStQkPYuwldjm
  secretkey: QLL06505pS
# static 폴더